apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-api-from-gh
  description: This is a sample API configuration for Backstage.
  tags:
    - sample
    - api
spec:
  type: openapi
  lifecycle: experimental
  owner: team-xyz
  definition:
    - $text: ./openapi.json
    - $text: ./openapi1.json
